import Head from 'next/head'
import styled from 'styled-components';
import Sidebar from '../components/Sidebar';

export default function Home() {
   return (
      <>
         <Head>
            <title>WhatsApp v2</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div>
            <Sidebar />
         </div>
      </>
   )
}
